### ISSUE TITLE
HTML emails don't work properly

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/webform#113]
When configuring Webform's global settings, I've enabled the options for HTML emails:

![screenshot-2018-7-5 webform settings packweb](https://user-images.githubusercontent.com/2385329/42312343-c5ae8c7e-8048-11e8-9df3-aa68baf3a117.png)

But emails that I've tested don't work properly - they seem to be in HTML format (e.g. they're not plain text), but the paragraph tags I've added to my Webform templates aren't working (all text is bunched together with no new lines between).

I suspect I need to enable a different module to support HTML emails (I remember that from Drupal), but this isn't documented anywhere in Webform...

So is this a bug, or a documentation issue?

**Comment by herbdool** [comment]
This will probably help: https://www.ostraining.com/blog/drupal/html-emails-from-drupal-webform/ and https://backdropcms.org/project/mimemail. Let me know if that works.

**Comment by ghost** [comment]
@herbdool I installed Mimemail and Simple Mailsystem and configured them both, but no change to the way webform emails are displayed...

In the email source, I can see `Content-Type: text/html; charset=UTF-8`, but no HTML tags whatsoever.

**Comment by herbdool** [comment]
Thanks for testing that @BWPanda. I don't have a lot of capacity to start investigating so I'm wondering if you feel like digging into this and working on a PR?

Do any HTML tags work at all? You mention that the emails are "not plain text" so I'm wondering how you can tell that.

**Comment by Graham-72** [comment]
Since you mention Mimemail and Simple Mailsystem, I plan to have a look at this during the next few days. It is a while since I checked out that these are working OK.

**Comment by ghost** [comment]
@herbdool Plain text emails display in a monospaced font for me in Thunderbird. These are displaying in the normal font, just without breaks, etc. Also there's the 'Content type' code in the source as above...

**Comment by Graham-72** [comment]
The situation would seem to be that if you want webform to send HTML messages that include the HTML layout tags you need to use it in conjunction with the Mimemail module which will then add the HTML formatting.

To get this working you need an entry in the system.mail config settings to direct the mail system to use the mimemail module for webform. A typical setting is`
`"webform": "MimeMailSystem"`

The alternative is to set the Default Mail System for your whole site to be Mimemail. This can be done with the Simple Mailsystem module.

It might be a good idea to add some code to Webform that puts an entry into system.mail.json so that it can be configured to use Mimemail. For more background see https://api.backdropcms.org/api/backdrop/core!includes!mail.inc/function/backdrop_mail_system.

A further possibility would be to use the mail class system so that webform sets the choice of mail system for each message, depending on whether it is HTML or not. I will work on a PR for this.

**Comment by Graham-72** [comment]
I have added PRs to address this issue. The first will add a config setting for Webform in system.mail and this will enable selection (by using a module such as Simple Mail System) of the mail system used for mail created by Webform.

The other PRs add a refinement so that mail created in Webform with the setting 'html' has the mail class 'webform_html' added to the config file system.mail, enabling plain and html mail to be handled by different mail systems.

@BWPanda are you still having the problem you described above?
>Plain text emails display in a monospaced font for me in Thunderbird. These are displaying in the normal font, just without breaks, etc.

I was having exactly the same problem but no longer see it, even before making the changes in these PRs.

**Comment by ghost** [comment]
I'm still having this issue. I decided to test on my sandbox site from scratch, here's what I did:

1. Installed Webform
2. Configured Webform (admin/config/content/webform)
   1. Ticked HTML mail system
   2. Set Format to HTML
3. Created Webform
   1. Added required textfield called Name
   2. Setup email to send to myself (default template includes `<p>` tags and Send E-mail As HTML is ticked)
4. Viewed the form and made a submission
5. Checked my email (all text is in one group; no paragraphs, line breaks, etc., source code contains `Content-Type: text/html; charset=UTF-8`, link where submission can be viewed is not clickable)
6. Installed Mime Mail (just default module)
7. Configured Mime Mail
   1. Entered Sender Name and Email Address
   2. Noted Email Format already set to Full HTML
8. Repeated steps 4 & 5 (same result)
9. Installed Simple Mailsystem
10. Configured Simple Mailsystem
    1. Site-wide Mail System already set to DefaultMailSystem
    2. Mimemail Class already set to MimeMailSystem
11. Repeated steps 4 & 5 (same result)

**Comment by Graham-72** [comment]
I will have a go at repeating this step by step, sometime in the next 2 or 3 days.

**Comment by Graham-72** [comment]
@BWPanda at step 10i please can you try using Simple Mailsystem to change the default mail system for the site to be Mimemail and then see what happens. I think that unless you do this the mail from Webform will not be passed to Mimemail. 

I still intend to work through your sequence.

**Comment by ghost** [comment]
> ... can you try using Simple Mailsystem to change the default mail system for the site to be Mimemail and then see what happens.

Ah, that worked! Thanks! So does that make this a bug or a documentation issue?

**Comment by Graham-72** [comment]
I'm not sure whether to call it a bug, though I think there is a deficiency in Webform relating to desirable settings in config system.mail and I have created two PRs to deal with this (numbers 116 and 117), as described above in comments on this issue.

If you want to use Mimemail for processing your emails, you can either set it as the default mail system for your site, and you can use Simple Mailsystem to do this without changing Webform.

However, if you want to set things so that Mimemail is not the default for your site but is used by Webform, then Webform needs to provide an entry in config system.mail so that it can be linked to the Mimemail module.

I will have a look at the documentation for both the Mimemail and Simple Mailsystem modules and clarify this.

If you were to want Webform to send email via yet another mail system, e.g. the SMTP module, then that would also require the appropriate setting in system.mail, and I will have a look to see whether this is available.

**Comment by Graham-72** [comment]
@BWPanda I have reached step 5 in your test sequence and I have the same problem with loss of line returns when I view the email. Then I un-checked the Webform setting 'Send email as HTML' and the line returns were there as intended. So my conclusion is that the default mail system in Backdrop will not handle the HTML and actually filters out the paragraph codes `<p> and </p>.` Hence the need to use the Mimemail module (or something else). Does that sound a reasonable conclusion?

**Comment by ghost** [comment]
@Graham-72 That sounds about right. Thanks for all your help with this!
