### ISSUE TITLE
Webform "Full content" View mode does not work in a block?

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/webform#12]
Hi! I am sorry if this is something of my fault but may be somebody could direct me to a right way :)

I try to show my Webform content in a block.
According to the instructions - "You may customize different view modes (other than the "Form only" mode)" - I have customized it to Full content but it does not work for me. After the block configuration is saved and the layout is saved too it switches back to the Form only mode.

I have tried to set up Full content mode for Webform block in Drupal 7 and there is no any problem - it works well.

![webform_full_content_1](https://cloud.githubusercontent.com/assets/13515302/9698815/e1670a0c-53cf-11e5-9547-ac1ff5511a3f.gif)

![webform_full_content_2](https://cloud.githubusercontent.com/assets/13515302/9698818/fe082fb0-53cf-11e5-985a-7dfb6c65570a.gif)

![webform_full_content_3](https://cloud.githubusercontent.com/assets/13515302/9698819/093879e4-53d0-11e5-8026-94a506526673.gif)

**Comment by Graham-72** [comment]
Hi @bd0bd 
I am interested in the question you raise here.
So far I have only used Webform once within Backdrop and so I cannot offer expert advice. In my case I was using the webform as a page but now I have tested using it as a block and I find that it works well, and it provides the form as a block that I can place on the page using the layouts feature in Backdrop.
I gather from what you say that you have done all this.

What I am wondering is, what more would 'full content' mode offer? What are you hoping to show on the page? I am thinking that because of use of layouts in Backdrop it will not be behaving the same way as in Drupal, but what is Drupal showing on the page that you are not seeing when using 'form only' mode in Backdrop?

**Comment by bd0bd** [comment]
Hi **Graham-72**
Sure, I can display Webform in a block.
But I would like to display the Webform page **together** with the content and photo it has.
With Drupal 7 I can do it.
How I can understand this should work exactly the same here with Backdrop.
But it does not work because of **a)** my fault; **b)** a bag or **c)** not completely done/ported Webform module (underdone) .

Thank you!

**Comment by Graham-72** [comment]
@bd0bd  Thanks, I understand now and have tried it myself. I think you have identified a fault, perhaps with webform but maybe with layouts. It could be that layouts is failing to accept the 'full content' setting. It definitely needs investigation.

**Comment by bd0bd** [comment]
**Graham-72** thank you!
May be somebody will solve this matter, I am too dummy to solve it myself :)

**Comment by bd0bd** [comment]
After trying to add block (Form only mode) I got this error:

![block2](https://cloud.githubusercontent.com/assets/13515302/9919996/54bd53fa-5cd9-11e5-9f28-13458e18de1a.gif)

**Comment by herbdool** [comment]
Can no longer replicate.
