### ISSUE TITLE
Project direction and webform 8.x

### ISSUE THREAD

**Issue by aydun** [backdrop-contrib/webform#161]
Apologies if this has been discussed elsewhere - if so, please point me to that.

What is the direction for this project as regards webform 8.x?  I see changes from the 7.x branch are regularly imported to the backdrop version but presumably development of that branch will dry up sometime. 

Webform 8.x starts from a different codebase and is designed for Drupal 8 so porting that to Backdrop is presumably a big task.

So is the intention for the Backdrop Webform to continue to track webform 7.x and evolve independently or is there any plan to adopt webform 8.x in some way?

**Comment by klonos** [comment]
Hello @aydun 👋 ...I will leave the last word to the module maintainers of the Backdrop version, but as far as I know all 7.x modules that are being ported will continue to be compatible with the Drupal 7 style of coding and APIs. So yes, I believe that you can think of the backdrop version as the continuation of the latest 7.x version of the module.

**Comment by herbdool** [comment]
Hi @aydun, good questions. We haven't had this discussion. Here are my thoughts. I believe that we will continue to track Webform 7.x as long as it gets updates. But we will also add new features where someone needs them and is able to contribute code to make them real. It's unlikely that we will take code directly from Webform 8 since it is quite different. It would be hard. But there might be some features which people want to replicate.

I personally do not have a lot of capacity to create new features now but I'm willing to help incorporate other people's code where it makes sense.

**Comment by aydun** [comment]
Thanks @klonos & @herbdool for those responses.  That seems a reasonable approach.  I've submitted https://github.com/backdrop-contrib/webform/pull/162 for new users trying to understand how this relates to the Drupal versions.

**Comment by stpaultim** [comment]
I stumbled across this "closed" issue with some interesting information about the future of this module. Since folks are unlikely to find this closed issue, I thought we might add some comments to this effect to the README file (seems like lots of people might have similar questions). 

I am reopening this issue until a decision is made on whether or not this update to the README makes sense. See attached PR. Please feel free to edit/adapt the text as you like. The maintainers might have a slightly different take on this, I just wanted to provide an easy starting point.

**Comment by herbdool** [comment]
Merged with some small edits - thanks @stpaultim
